# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Data
    url: /data
    weight: 10
  - name: Tools
    url: /tools
    weight: 20
  - name: Docs
    url: "https://docs.openforestobservatory.org"
    weight: 30
  - name: About
    weight: 40
    url: /about
